name: ai_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/